name: 'Update ophan-thrift-swift'
description: 'Automatically generates Swift Thrift classes (for Ophan tracking) in the iOS Live App'
inputs:
  # For example usage, see https://github.com/guardian/ophan/pull/7248
  app-token:
    description: 'GitHub App installation token'
    required: true
  app-slug:
    description: 'GitHub App slug'
    required: true
  app-user-id:
    description: 'GitHub App user ID'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-token }}
    - ${{ inputs.app-slug }}
    - ${{ inputs.app-user-id }}
