/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// Represents the rendering of an ad on this page.
public final class RenderedAd {

  /// The name of the ad slot in which this ad was rendered.
  public var slot: String

  /// The DFP line item id populated in this slot.
  public var lineItemId: Int64?

  /// The DFP creative id populated in this slot.
  public var creativeId: Int64?

  /// The approximate amount of time (in milliseconds) that this
  /// ad took to render.
  public var timeToRenderEndedMs: Int64?

  /// The approximate amount of time (in milliseconds) that elapsed
  /// before this ad was requested.
  public var timeToAdRequestMs: Int64?

  /// The approximate amount of time (in milliseconds) between requesting
  /// and receiving this ad.
  public var adRetrievalTimeMs: Int64?

  /// The approximate amount of time (in milliseconds) between receiving
  /// and rendering this ad.
  public var adRenderTimeMs: Int64?


  public init(slot: String) {
    self.slot = slot
  }

  public init(slot: String, lineItemId: Int64?, creativeId: Int64?, timeToRenderEndedMs: Int64?, timeToAdRequestMs: Int64?, adRetrievalTimeMs: Int64?, adRenderTimeMs: Int64?) {
    self.slot = slot
    self.lineItemId = lineItemId
    self.creativeId = creativeId
    self.timeToRenderEndedMs = timeToRenderEndedMs
    self.timeToAdRequestMs = timeToAdRequestMs
    self.adRetrievalTimeMs = adRetrievalTimeMs
    self.adRenderTimeMs = adRenderTimeMs
  }

}


