/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// Where the referrer was google and they've provided additional information
/// on the query string, here is
/// that additional information.
public final class GoogleReferral {

  /// The query terms requested by the user
  public var q: String?

  /// The rank we were list at within the source, as indicated by the "cd" query
  /// parameter.
  public var rank: Int32?

  /// The type of referral this was. Currently this is just a string, and is likely to
  /// change as we overhaul our google ved parsing
  public var source: String?


  public init() { }
  public init(q: String?, rank: Int32?, source: String?) {
    self.q = q
    self.rank = rank
    self.source = source
  }

}


