/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public final class InPageClick {

  /// the component that contained the item clicked on
  public var component: String?

  /// The link name associated with the element clicked.
  public var linkName: LinkName?


  public init() { }
  public init(component: String?, linkName: LinkName?) {
    self.component = component
    self.linkName = linkName
  }

}


