/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// Represents an interaction on the web or apps
public final class Interaction {

  /// Key for the interaction.
  public var component: String

  /// Value associated with the interaction
  public var value: String?

  /// The id of the atom that the interaction has come from
  public var atomId: String?


  public init(component: String) {
    self.component = component
  }

  public init(component: String, value: String?, atomId: String?) {
    self.component = component
    self.value = value
    self.atomId = atomId
  }

}


