/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// Extra parameters only applicable to print products
public final class PrintOptions {

  /// Differentiates between the (many) different types of print product
  public var product: PrintProduct

  /// The deliver country of the print subscription
  public var deliveryCountryCode: String


  public init(product: PrintProduct, deliveryCountryCode: String) {
    self.product = product
    self.deliveryCountryCode = deliveryCountryCode
  }

}


