/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// A product event that is not necessarily tied to a pageview.
public final class NativeProductEvent {

  /// A stable event name, e.g. "consent_screen".
  public var name: String

  /// Event-specific attributes that Ophan cannot derive from the native app submission wrapper.
  public var attributes: TMap<String, String>?


  public init(name: String) {
    self.name = name
  }

  public init(name: String, attributes: TMap<String, String>?) {
    self.name = name
    self.attributes = attributes
  }

}

/// A product event enriched by Ophan with common metadata from the native app submission wrapper.
public final class ProductEvent {

  /// A stable event name, e.g. "consent_screen".
  public var name: String

  /// Event-specific attributes that Ophan cannot derive from the native app submission wrapper.
  public var attributes: TMap<String, String>?

  /// Common analysis dimensions derived by Ophan from the native app submission wrapper.
  public var metadata: TMap<String, String>


  public init(name: String, metadata: TMap<String, String>) {
    self.name = name
    self.metadata = metadata
  }

  public init(name: String, attributes: TMap<String, String>?, metadata: TMap<String, String>) {
    self.name = name
    self.attributes = attributes
    self.metadata = metadata
  }

}


