/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


public func ==(lhs: NativeProductEvent, rhs: NativeProductEvent) -> Bool {
  return
    (lhs.name == rhs.name) &&
    (lhs.attributes == rhs.attributes)
}

extension NativeProductEvent : CustomStringConvertible {

  public var description : String {
    var desc = "NativeProductEvent("
    desc += "name=\(String(describing: self.name)), "
    desc += "attributes=\(String(describing: self.attributes))"
    return desc
  }

}

extension NativeProductEvent : Hashable {

  public func hash(into hasher: inout Hasher) {
    hasher.combine(name)
    hasher.combine(attributes)
  }

}

extension NativeProductEvent : TStruct {

  public static var fieldIds: [String: Int32] {
    return ["name": 1, "attributes": 2, ]
  }

  public static var structName: String { return "NativeProductEvent" }

  public static func read(from proto: TProtocol) throws -> NativeProductEvent {
    _ = try proto.readStructBegin()
    var name: String!
    var attributes: TMap<String, String>?

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case (1, .string):           name = try String.read(from: proto)
        case (2, .map):             attributes = try TMap<String, String>.read(from: proto)
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()
    // Required fields
    try proto.validateValue(name, named: "name")

    return NativeProductEvent(name: name, attributes: attributes)
  }

}



public func ==(lhs: ProductEvent, rhs: ProductEvent) -> Bool {
  return
    (lhs.name == rhs.name) &&
    (lhs.attributes == rhs.attributes) &&
    (lhs.metadata == rhs.metadata)
}

extension ProductEvent : CustomStringConvertible {

  public var description : String {
    var desc = "ProductEvent("
    desc += "name=\(String(describing: self.name)), "
    desc += "attributes=\(String(describing: self.attributes)), "
    desc += "metadata=\(String(describing: self.metadata))"
    return desc
  }

}

extension ProductEvent : Hashable {

  public func hash(into hasher: inout Hasher) {
    hasher.combine(name)
    hasher.combine(attributes)
    hasher.combine(metadata)
  }

}

extension ProductEvent : TStruct {

  public static var fieldIds: [String: Int32] {
    return ["name": 1, "attributes": 2, "metadata": 3, ]
  }

  public static var structName: String { return "ProductEvent" }

  public static func read(from proto: TProtocol) throws -> ProductEvent {
    _ = try proto.readStructBegin()
    var name: String!
    var attributes: TMap<String, String>?
    var metadata: TMap<String, String>!

    fields: while true {

      let (_, fieldType, fieldID) = try proto.readFieldBegin()

      switch (fieldID, fieldType) {
        case (_, .stop):            break fields
        case (1, .string):           name = try String.read(from: proto)
        case (2, .map):             attributes = try TMap<String, String>.read(from: proto)
        case (3, .map):             metadata = try TMap<String, String>.read(from: proto)
        case let (_, unknownType):  try proto.skip(type: unknownType)
      }

      try proto.readFieldEnd()
    }

    try proto.readStructEnd()
    // Required fields
    try proto.validateValue(name, named: "name")
    try proto.validateValue(metadata, named: "metadata")

    return ProductEvent(name: name, attributes: attributes, metadata: metadata)
  }

}



