/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import Foundation

import Thrift


/// A query string parameter
public final class QueryParameter {

  /// The name of the query string parameter
  public var name: String

  /// The value of the query string parameter
  public var value: String


  public init(name: String, value: String) {
    self.name = name
    self.value = value
  }

}


